# Generated by Django 4.2 on 2023-06-28 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_alter_author_authoruser_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, max_length=64, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
