# Generated by Django 4.2 on 2023-06-30 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduserscategory',
            old_name='postCategory',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='subscribeduserscategory',
            old_name='subscribers',
            new_name='subscribed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
