# Generated by Django 4.2 on 2023-07-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_postcategory_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='/photos/def/1.jpg/', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Покупка'), ('AR', 'Продажа')], default='AR', max_length=2),
        ),
    ]
