# Generated by Django 4.2 on 2023-07-22 21:43

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_post_photo_alter_post_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.FileField(blank=True, default='/photos/def/1.jpg/', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),

    ]
