# Generated by Django 4.2 on 2023-08-13 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_remove_post_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('A', 'Принята'), ('D', 'Отклонена'), ('N', 'Ожидание')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comment', through='news.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
