# Generated by Django 4.2 on 2023-08-17 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0020_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='user_sender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='respond',
            field=models.ManyToManyField(related_name='post_responses', through='news.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
