# Generated by Django 4.2 on 2023-08-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_rename_commentuser_comment_user_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('A', 'Принята'), ('D', 'Отклонена'), ('N', 'Ожидание')], default='N', max_length=1),
        ),
    ]
