# Generated by Django 4.2 on 2023-08-24 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0022_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(choices=[(False, 'Отклонена'), (True, 'Принята')], default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='respond',
            field=models.ManyToManyField(related_name='post_comment', through='news.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
