# Generated by Django 4.2 on 2023-07-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
